Near-One/near-plugins

near-plugins/src/test_utils.rs

Without these changes integration tests in `near-plugins/tests` don't compile (in my setup).

Fix compilation of integration tests

---

near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/access_controllable.rs
near-plugins/tests/common/access_controllable_contract.rs

__Note__ To be merged after #8 and #9. Once they are merged, I'll rebase this PR. Until then, the diff here on github is messy (hence still in draft mode). After the rebase, only the most recent commit should remain in this PR.
Adds methods to retrieve the admins and grantees of roles.
- Trait methods are added to AccessControllable:
- `acl_get_admins`
- `acl_get_grantees`
- The attribute `#[access_controllable]` adds implementations of these methods.
- The new methods are tested in `near-plugins/tests/access_controllable.rs`
```
cargo test --test access_controllable
du --summarize --total --human-readable /tmp/sandbox-*
rm -r /tmp/sandbox-*
```

Add functions acl_get_{admins, grantees}

---

near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

__Note__: To be merged after #8. Once #8 is merged I'll rebase this PR, until then the diff here on github is messy: Only the two most recent commits will remain in this PR, previous commits belong to #8.
- Trait methods are added to `AccessControllable`:
- `acl_grant_role`
- `acl_revoke_role`
- `acl_renounce_role`
- `acl_revoke_role_unchecked`
- The attribute `#[access_controllable]` adds implementations of these methods.
- The new methods are tested in `near-plugins/tests/access_controllable.rs`
```
cargo test --test access_controllable
du --summarize --total --human-readable /tmp/sandbox-*
rm -r /tmp/sandbox-*
```

Add functions to manage Acl roles

---

near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

Contract developers need some way to add an initial super-admin. Having a method for that in the trait (opposed to calling a method on an internal type) makes documentation and examples simpler.
CC @mfornet since we discussed this offline.

Add fn acl_init_super_admin to trait AccessControllable

---

near-plugins-derive/src/access_controllable.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

Currently passing the `role_type` argument into `#[access_control]` requires quotes around `Role`:
```rust
#[access_control(role_type = "Role")]
#[near_bindgen]
#[derive(Default, BorshDeserialize, BorshSerialize)]
pub struct Contract { /* ... */ }
```
Requiring quotes around the identifier looks not so nice.
After this update the quotes can be omitted and the syntax changes to:
```rust
#[access_control(role_type(Role))]
```

Update syntax to pass `role_type` to acl

---

near-plugins-derive/src/access_controllable.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

Previously contract developers needed to bring traits into scope to allow the code generated for acl to call methods of some traits:
- `std::convert::TryFrom` for method `try_from`
- `near_plugins::events::AsEvent` for method `emit`
In this PR, calls to above methods are changed to fully qualified syntax. As a result, the traits no longer need to be brought into scope with `use` statements.

Make calls to trait methods fully qualified in acl plugin

---

near-plugins-derive/src/pausable.rs

Use __check_paused to avoid collision with local variables.
Closes #17

Use double underscore in generated variables

---

near-plugins-derive/src/access_control_role.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

fix: doc comment on Role variant crashes macro

---

near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/access_controllable.rs
near-plugins/tests/common/access_controllable_contract.rs

There was not method to retrieve super-admins in trait `AccessControllable`.
This PR adds `acl_get_super_admins`.

Add fn acl_get_super_admins to trait AccessControllable

---

Cargo.toml
near-plugins-derive/src/access_controllable.rs

This only affects the Acl plugin, other plugins aren't using `near_sdk::collections`.
`near_sdk::collections` [will be put under the legacy feature flag](https://github.com/near/near-sdk-rs/pull/923) and its successor is `near_sdk::store`. Once a contract uses a plugin based on `collections`, it will require efforts to migrate that contract to a new plugin version based on `store`. To avoid that, let's migrate `near-plugins` itself to `near_sdk::store` before any plugins are used in production.
Main differences to `near_sdk::collections` are described in the last section of [this post](https://github.com/near/near-sdk-rs/discussions/829).
To use `store` it's currently still required to enable the `unstable` feature for `near_sdk`. Seems like `store` will be stabilized in sdk version 4.1 …

Migrate from `near_sdk::collections` to `near_sdk::store`

---

Cargo.toml

Benefits:
- Stabilizes `near-sdk::store`, so `unstable` is not needed anymore for `near-sdk`.
- Includes an update that allows closing #39.
The entire near-sdk changelog is available [here](https://github.com/near/near-sdk-rs/blob/master/CHANGELOG.md).

build(deps): update near-sdk to 4.1.0

---

README.md

- Add general links at the top, to provide an overview.
- Add links specific to each plugin.
I would suggest landing #42 first.

Make docs and examples more accessible

---

README.md

An introduction of the Acl plugin was missing - it was still listed unter Roadmap.
Closes #41

Add Acl plugin to the Readme

---

README.md
near-plugins-derive/src/access_control_role.rs
near-plugins-derive/src/access_controllable.rs
near-plugins-derive/src/lib.rs
near-plugins-derive/src/pausable.rs
near-plugins/src/pausable.rs

Previously the `Pausable` plugin required a contract to be `Ownable` to manage authorization of (un)pausing features and to define exemptions via `except`. This PR makes `Pausable` use `AccessControllable` instead of `Ownable`.
- Developers specify which Acl role(s) can pause and unpause features.
- When using `except` with `#[pause]` or `#[if_paused]`, developers can specify Acl role(s) which are exempted.
Files in [examples/pausable-examples/](/examples/pausable-examples/) have not been updated, for now. I'd propose to remove the contracts there and instead add a test contract in `/near-plugins/tests/contracts/pausable`, see #48.
I suggest we first decide if this is a reasonable approach before updating examples.

Make Pausable use Acl for authorization

---

README.md
near-plugins/src/pausable.rs

Explain why `AccessControllable` is used and hint that it's methods should be used to grant and revoke permissions.

docs: Add details of Pausable integration with Acl

---

near-plugins/src/pausable.rs

Adds a unit test to verify the behaviour mentioned above.
Motivation:
- Verify and document the behavior.
- Have a test that fails if the behavior changes by accident.

test: Pausable `except` works when `ALL` is paused

---

README.md
near-plugins-derive/src/access_control_role.rs
near-plugins-derive/src/access_controllable.rs
near-plugins-derive/src/full_access_key_fallback.rs
near-plugins-derive/src/lib.rs
near-plugins-derive/src/ownable.rs
near-plugins-derive/src/pausable.rs
near-plugins-derive/src/upgradable.rs
near-plugins-derive/src/utils.rs
near-plugins/src/access_control_role.rs
near-plugins/src/events.rs
near-plugins/src/full_access_key_fallback.rs
near-plugins/src/ownable.rs
near-plugins/src/pausable.rs
near-plugins/src/upgradable.rs

Describes the internal architecture and testing approach in the README.
Ensures all `pub` items in `near-plugins` and `near-plugins-derive` have doc comments.

docs: describe architecture & testing; add doc comments

---

near-plugins/tests/contracts/pausable/src/lib.rs

The constructor of the test contract for `Pausable` adds the contract itself as Acl super admin. It was using `predecessor_account_id()`, though it should be `current_account_id()`.
It didn't surface as bug in integration tests since there the constructor is called by the contract itself (so predecessor id equals current account id).

fix: super admin init in Pausable test contract

---

near-plugins/tests/access_controllable.rs
near-plugins/tests/contracts/access_controllable/src/lib.rs

The combination of role names and methods names in the test/demo contract for `AccessControllable` was confusing.
For the review I'd recommend looking at the contract (`lib.rs`) first, the changes in `tests/access_controllable.rs` should then be straightforward.

refactor: names of methods and roles in the Acl contract

---

near-plugins/src/ownable.rs

...and describe the workaround mentioned by @birchmd.
Closes #58

docs: mention `Ownable::owner_is` fails in view calls

---

near-plugins/tests/access_controllable.rs
near-plugins/tests/common/utils.rs
near-plugins/tests/ownable.rs
near-plugins/tests/pausable.rs

This PR fixes errors found by clippy when run on `near-plugins/tests`. Currently CI is not checking tests, see #23. Once this PR is merged, we can merge #23 to make CI check tests.
The errors fixed here were found with the following command:
```
cargo clippy --all --all-features --all-targets -- -D warnings
```

chore: fix clippy errors in `near-plugins/tests`

---

.github/workflows/test.yml

Previously clippy did not check tests. There were some issues which have been fixed in #63.

ci: make clippy check tests

---

Cargo.toml

This allows to [view_access_keys](https://docs.rs/workspaces/0.7.0/workspaces/struct.Contract.html#method.view_access_keys) of a `Contract`, which is helpful for testing `FullAccessKeyFallback::attach_full_access_key`.
Other changes in `workspaces` require no action items for this repo.
---
Feature `unstable` can be removed since we’re no longer using `workspaces::compile_project` (#15).

build(deps): bump `workspaces` from `0.6` to `0.7`

---

near-plugins/src/access_controllable.rs

Mention that an admin may revoke permissions from any other admin for the same role.

docs: extend `acl_revoke_admin` docs

---

near-plugins-derive/src/ownable.rs

At first glance, it may look like the block containing the `std::panic!` is injected into smart contracts. This PR adds a comment to explain what happens.

docs: justify a usage of `std::panic!`

---

near-plugins/src/upgradable.rs

- Describes how contracts with vulnerable code might mitigate risks when using `Upgradable`.
- Does some language reworks of preceding sections (doing that in a separate PR might be too much overhead).

docs: add notes on upgrading vulnerable code

---

near-plugins-derive/src/access_control_role.rs
near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_control_role.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/access_controllable.rs
near-plugins/tests/common/access_controllable_contract.rs

- Allows introspection by feeding roles retrieved via `acl_role_variants` into `acl_get_{admins, grantees}`.
- Is a building block for further introspection methods to be added soon.

feat: add Acl introspection of role variants

---

near-plugins-derive/src/access_controllable.rs
near-plugins/src/access_controllable.rs
near-plugins/tests/access_controllable.rs
near-plugins/tests/common/access_controllable_contract.rs
near-plugins/tests/common/utils.rs

Adds method `acl_get_permissioned_accounts` which returns information about _all_ outstanding permissions.
This method will be available on every contract that implements `AccessControllable`.

feat(AccessControllable): add `acl_get_permissioned_accounts`

---

README.md
near-plugins-derive/src/upgradable.rs
near-plugins-derive/tests/contracts/upgradable/src/lib.rs
near-plugins-derive/tests/contracts/upgradable_2/src/lib.rs
near-plugins-derive/tests/upgradable.rs
near-plugins/src/upgradable.rs

Previously `Upgradable` authorization was handled by `Ownable`. An explanation of how to use `Upgradable` with Acl is available in the [example contract](https://github.com/aurora-is-near/near-plugins/blob/d5096361fa42ea21b82f0d071497400f357919eb/near-plugins-derive/tests/contracts/upgradable/src/lib.rs).
Use cases which don’t require fine grained permissions can define only a single role and whitelist it for all `Upgradable` features. See `Role::DAO` in the example contract.
The other roles show how to achieve more fine grained permissions by whitelisting a role only for a subset of the `Upgradable` features.

feat(Upgradable)!: use Acl for authorization 

---

near-plugins-derive/src/upgradable.rs
near-plugins-derive/tests/common/upgradable_contract.rs
near-plugins-derive/tests/common/utils.rs
near-plugins-derive/tests/contracts/upgradable_state_migration/Cargo.toml
near-plugins-derive/tests/contracts/upgradable_state_migration/Makefile
near-plugins-derive/tests/contracts/upgradable_state_migration/rust-toolchain
near-plugins-derive/tests/contracts/upgradable_state_migration/src/lib.rs
near-plugins-derive/tests/upgradable.rs
near-plugins/src/upgradable.rs

Closes #76 and this [external issue](https://github.com/AuditoneCodebase/Aurora-audit-review/issues/27).
Adds an additional parameter to `Upgradable::up_deploy_code` that allows to optionally specify a function call to be batched with the code deployment. This might be a function that migrates state. If that function call fails, the deployment is rolled back and the old code remains active.
This is a breaking change since it modifies the signature of `Upgradable::up_deploy_code`. Users that want to maintain the previous behavior (deployment without function call) can migrate in the following way:
```rust
// Previously:
up_deploy_code()
// Same behavior with the new API:
up_deploy_code(None)
```

feat(Upgradable)!: enable batched fn call after deploy

---

near-plugins-derive/tests/upgradable.rs
near-plugins/src/upgradable.rs

Makes it more explicit how staged code can be removed after it was deployed. Mentions the benefit of freeing storage.
Related to [this issue](https://github.com/AuditoneCodebase/Aurora-audit-review/issues/9) and its comment.

docs(Upgradable): code removal after deplyoment

---

near-plugins-derive/src/pausable.rs
near-plugins-derive/tests/pausable.rs
near-plugins/src/pausable.rs

Makes `pa_pause` and `pa_unpause` return a `bool` that indicates whether the feature is newly (un)paused. This corresponds to the return values of `std::collections::HashSet` methods [insert](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.insert) and [remove](https://doc.rust-lang.org/std/collections/struct.HashSet.html#method.remove).
Closes this [external issue](https://github.com/AuditoneCodebase/Aurora-audit-review/issues/32).
This PR also changes event emitting behavior. Sneaking it into this PR since it only reorders code in the two functions that are modified here.
Previously events `Pause` and `Unpause` were emitted even if:
- State was not modified since the feature was alreay (un)paused.
- The function panicked because state could not be serialized.
To …

feat(Pausable)!: make `pa_[un]pause` return `bool`

---

near-plugins-derive/src/access_controllable.rs
near-plugins-derive/tests/access_controllable.rs
near-plugins-derive/tests/common/access_controllable_contract.rs
near-plugins/src/access_controllable.rs

Currently, the ACL plugin provides api to init single super admin by `acl_init_super_admin`. But to transfer the admin to another account, the developers need to write their own method, like this:
```
pub fn transfer_super_admin(&mut self, account_id: AccountId) {
let current_super_admin = env::predecessor_account_id();
near_sdk::require!(
self.acl_get_or_init()
.revoke_super_admin_unchecked(&current_super_admin),
"Failed to revoke super-admin."
);
near_sdk::require!(
self.acl_get_or_init().init_super_admin(&account_id),
"Failed to init super-admin."
);
}
```
This pull request adds a default implementation to transfer the super admin permissions to another account, this could be useful for transferring the super admin to DAO or another account, or on migration from one DAO to another. …

ACL: Add transfer super admin api

---

near-plugins-derive/src/ownable.rs
near-plugins-derive/src/pausable.rs

Use the `emit` method to cleanup code and avoid duplicating logging logic.

chore: use `emit` to log events

---

near-plugins/src/upgradable.rs

Using the `Upgradable` plugin makes sense when there are no other ways to deploy code. Under that assumption stale staged code is equal to deployed code and the statement removed in this PR is confusing.
With this change the section `# Stale staged code` in the module documentation becomes very short. Still I think it makes sense to keep it there, to highlight the importance of handling stale staged code.

docs(Upgradable): remove confusing statement

---

near-plugins-derive/src/access_controllable.rs
near-plugins-derive/tests/access_controllable.rs
near-plugins-derive/tests/common/access_controllable_contract.rs
near-plugins/src/access_controllable.rs

Adds the function to the `AccessControllable` trait and provides a default implementation.
Previously super-admins could be added only via `acl_init_super_admin` and `add_super_admin_unchecked`, which is an internal function of the default implementation.
`acl_add_super_admin` allows adding multiple super-admins without having to use internal functions.

feat(Acl): add `acl_add_super_admin`

---

near-plugins/src/access_controllable.rs

A top level overview was missing in `near-plugins/access_controllable.rs`. All other files defining plugin traits have it.

docs(Acl): add module-level docs

---

near-plugins-derive/tests/common/key.rs
near-plugins-derive/tests/common/mod.rs
near-plugins-derive/tests/common/utils.rs
near-plugins-derive/tests/ownable.rs

Adds a test to verify that that the account of an `Ownable` contract cannot set a new owner after its access keys are removed.

test(Ownable): removing contract keys freezes owner

---

near-plugins-derive/src/access_controllable.rs

Reorders the state modifications in `acl_transfer_super_admin` as suggested in [this comment](https://github.com/aurora-is-near/near-plugins/pull/94#discussion_r1137435879).

refactor(Acl): reorder state modifications

---

near-plugins-derive/src/access_controllable.rs

The ToDo refers to PR #12.
As it was merged, the code can be updated there.
In such a way, some unnecessary actions are performed (`.iter().skip(0).take(1).cloned().collect()`).
However, the code looks clearer.
The change does not break any tests.
If the PR would not be accepted, the ToDo should be reworked or removed.

Fulfill TODO

---

near-plugins/src/CHANGELOG.md

Adds a change log containing the changes for the next release since [0.0.2](https://github.com/aurora-is-near/near-plugins/releases).
Proposes to bump the version to 0.1.0, since there are a number of breaking changes. Before going to 1.0.0 we probably want to wait if there’s any feedback from usage in production.

docs: add a change log

---

Cargo.toml
near-plugins-derive/Cargo.toml
scripts/fix_dependencies.sh

`near-plugins-derive` was the only workspace member that depended on `borsh`. However, it isn’t actually used. Instead `borsh` re-exported by `near-sdk` is used, which is considered [best practice](https://docs.near.org/sdk/rust/best-practices#reuse-crates-from-near-sdk). Removing the `borsh` dependency might also prevent using it accidentally (instead of `borsh` re-exported by `near-sdk`) in the future.

build: only use `borsh` re-exported by `near-sdk`

---

Cargo.toml
near-plugins-derive/tests/contracts/access_controllable/Cargo.toml
near-plugins-derive/tests/contracts/ownable/Cargo.toml
near-plugins-derive/tests/contracts/pausable/Cargo.toml
near-plugins-derive/tests/contracts/upgradable/Cargo.toml
near-plugins-derive/tests/contracts/upgradable_2/Cargo.toml
near-plugins-derive/tests/contracts/upgradable_state_migration/Cargo.toml
scripts/fix_dependencies.sh

Building tests may currently fail since a dependency of `near-sdk` v4.1.1 (most recent release) has been yanked. Providing a patch is the [recommended workaround](https://github.com/near/near-sdk-rs/issues/1119#issuecomment-1889323112).
A new version of `near-sdk` is planned to be released soon. Then this patch shouldn’t be required anymore ([ref.](https://github.com/near/near-sdk-rs/issues/1119#issuecomment-1889323112)). 
By now more recursive dependencies need to be downgraded manually for tests to build with MSRV 1.69.0. See [this comment](https://github.com/aurora-is-near/near-plugins/pull/118#issuecomment-1794576809) for details.

build: add workarounds required to build tests

---

CHANGELOG.md
Cargo.toml

Motivation for doing a new release:
- Tests might not be built for the current release ([ref](https://github.com/aurora-is-near/near-plugins/pull/118)).
- An [article](https://github.com/mooori/counter-acl-example/pull/1) on `near-plugins` is planned to be published soon and it would be good to release recent changes before that.

Prepare release of v0.2.0

---

.github/workflows/test.yml
Cargo.toml
README.md
near-plugins-derive/src/access_control_role.rs
rust-toolchain

I think this repo should not set a `channel` for [these reasons](https://github.com/aurora-is-near/near-plugins/pull/131/commits/d3b3ddfd4e18bb1aa055aa1ba61fe39791f2c550). Since by now users can be expected to have a default Rust toolchain >= 1.70 installed, it would also help to avoid issues like #130.
- The README now encourages developers to locally set `channel = <MSRV>`
- #132 points users that have to work with 1.69 to required fixes.
Make CI install the toolchain to be used in tests right away by setting `toolchain: <MSRV>` in `test.yml`.

build: stop pinning a toolchain version

---

Cargo.toml
near-plugins-derive/src/pausable.rs
near-plugins-derive/tests/common/utils.rs
near-plugins-derive/tests/contracts/pausable/src/lib.rs
near-plugins-derive/tests/pausable.rs

- Skip role verifications if the pausable method doesn't contain except roles to able to call view methods.
- Fix the `near-sdk` version to avoid auto upgrade that breaks CI and build due to dependencies conflicts.

fix: make view methods pausable

---

.github/workflows/test.yml
Cargo.toml
near-plugins-derive/tests/contracts/access_controllable/rust-toolchain
near-plugins-derive/tests/contracts/ownable/rust-toolchain
near-plugins-derive/tests/contracts/pausable/rust-toolchain
near-plugins-derive/tests/contracts/upgradable/rust-toolchain
near-plugins-derive/tests/contracts/upgradable_2/rust-toolchain
near-plugins-derive/tests/contracts/upgradable_state_migration/rust-toolchain

Hey Team!
This PR removes limitation on the minor version of `near-sdk` as it prevents people from updating `near-sdk` to the latest version, while the real version pinning should be done in `Cargo.lock` for every binary crate, IMHO

fix: remove the limit on minor version from `near-sdk` dependency

---

near-plugins/src/access_controllable.rs
near-plugins/src/upgradable.rs

This PR fixes an issue when ABI generation fails due to absence of `#[derive(JsonSchema)]`
```sh
cargo near build
• Generating ABI
│ error[E0277]: the trait bound `PermissionedAccounts: JsonSchema` is not satisfied
│     |
│ 18  | #[access_control(role_type(Role))]
│     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
│     | |
│     | the trait `JsonSchema` is not implemented for `PermissionedAccounts`
│     | required by a bound introduced by this call
│     |
│     = help: the following other types implement trait `JsonSchema`:
│               &'a T
│               &'a mut T
│               ()
│               (T0, T1)
│               (T0, T1, T2)
│               (T0, T1, T2, T3)
│               (T0, T1, T2, T3, T4)
│               (T0, T1, T2, T3, T4, T5)
│             and 185 others
│ note: …
```

fix: ABI generation

---

.github/workflows/test.yml
Cargo.toml
near-plugins-derive/src/upgradable.rs
near-plugins-derive/tests/contracts/access_controllable/rust-toolchain
near-plugins-derive/tests/contracts/ownable/rust-toolchain
near-plugins-derive/tests/contracts/pausable/rust-toolchain
near-plugins-derive/tests/contracts/upgradable/rust-toolchain
near-plugins-derive/tests/contracts/upgradable_2/rust-toolchain
near-plugins-derive/tests/contracts/upgradable_state_migration/rust-toolchain
near-plugins-derive/tests/upgradable.rs
near-plugins/src/access_controllable.rs
near-plugins/src/upgradable.rs

If the migration is missed during the upgrade, it cannot be recovered. Therefore, the contract state will be corrupted, and the upgrade cannot be repeated.
There are two ways to prevent this:
- Remove the `self` everywhere from the near-plugins [example](https://github.com/Near-One/near-plugins/commit/8a354743525806671061aae2e6833836a91ec7e0).
- Verify the state after migration by default.
The second one is less invasive, so this PR implements it.

feat: make the upgrade process safer

---

CHANGELOG.md
docs/migrations/pausable-separate-roles.md
near-plugins-derive/src/pausable.rs
near-plugins-derive/tests/contracts/pausable/src/lib.rs
near-plugins-derive/tests/pausable.rs
near-plugins/src/pausable.rs

Replaces the single `manager_roles` attribute with separate `pause_roles` and `unpause_roles` attributes in the Pausable plugin. This enables assigning different permissions for pausing and unpausing features.
- Modified `pausable.rs` trait and implementation to support separate role specifications
- Updated test contracts and tests
- Added migration documentation and CHANGELOG entry
```rust
// Before
#[pausable(manager_roles(Role::PauseManager))]
// After
#[pausable(
pause_roles(Role::PauseManager),
unpause_roles(Role::UnpauseManager)
)]
```
Breaking change that requires code updates when upgrading. This enables more granular security policies, particularly in scenarios where emergency pausing should be available to more accounts than unpausing.
- Closes #151
- Closes #124

feat: Separate pause and unpause roles in Pausable plugin

---

near-plugins-derive/src/upgradable.rs
near-plugins-derive/tests/contracts/upgradable_state_migration/src/lib.rs
near-plugins-derive/tests/upgradable.rs

close https://github.com/Near-One/near-plugins/issues/158

chore: verify the state after wrong migration
